CREATE SEQUENCE demo_sequence2
INCREMENT BY 1
START WITH 1
NO MAXVALUE
NO MINVALUE
NO CYCLE
NO CACHE
NO ORDER;

-- Commented lines with keywords 'NOCACHE', 'ORDER' and 'NOORDER'

-- CREATE SEQUENCE demo_sequence2
-- INCREMENT BY 1
-- START WITH 1
-- NOMAXVALUE
-- NOMINVALUE
-- NOCYCLE
-- NOCACHE
-- NOORDER;