CREATE FUNCTION test.MyUDF1(a INT64, b INT64, c INT64)
  RETURNS INT64
  LANGUAGE SQL
  CONTAINS SQL
  DETERMINISTIC
  COLLATION INVOKER
  INLINE TYPE 1
  RETURN a * b * c;

CREATE FUNCTION test.MyUDF2(d INT64, e INT64, f INT64)
  RETURNS INT64
  LANGUAGE SQL
  CONTAINS SQL
  DETERMINISTIC
  COLLATION INVOKER
  INLINE TYPE 1
  RETURN d + e + f;